language: php
php:
- '7.1'

script:
  - if [[ $TRAVIS_PULL_REQUEST != 'false' ]]; then printf "Build\n" ; printf "Unit tests\n"; printf "Create the artifact\n"; printf "Deploy staging\n" else printf "Not in s PR" ; fi

