language: php
php:
- '7.1'

script:
  - if [[ $TRAVIS_PULL_REQUEST -ne 'false' ]]; then printf "Build\n" ; printf "Unit tests\n"; printf "Create the artifact for commit $TRAVIS_COMMIT\n"; printf "Deploy staging $TRAVIS_COMMIT\n"; else printf "Not in PR\n" ; fi
  - if [[ $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_BRANCH = "master" ]]; then printf "Deploy prod $TRAVIS_COMMIT\n" ; fi

